### ISSUE TITLE
Work On making UI better 

### ISSUE THREAD

**Issue by adyasha9** [adyasha9/nodejs-chatbot#2]
provide screenshots of the updated UI in the comment section.
If you want to do major changes please raise an issue first.

**Comment by miikkasaxlund** [comment]
I'd like to help you with this issue. I'll provide some screenshots as soon as I'm finished

**Comment by adyasha9** [comment]
@miikkasaxlund okay thanks!

**Comment by asrgabreo** [comment]
I'd like to help you and soon provide screenshots  when I'm finished

**Comment by adyasha9** [comment]
@asrgabreo thanks!

**Comment by miikkasaxlund** [comment]
Okay so I've made quick mockups with Adobe XD, and would like you to review them

This is the desktop layout
![UI - Desktop](https://user-images.githubusercontent.com/23664913/95112148-41084480-0749-11eb-9848-5fb8a27f1730.png)

And this is the mobile layout
![UI - Mobile](https://user-images.githubusercontent.com/23664913/95112328-744ad380-0749-11eb-9df6-ee967680e189.png)

If the style is not something you're looking for, just let me know before I start making any changes to the source code

**Comment by adyasha9** [comment]
@miikkasaxlund  I like it very much! Thank you!

**Comment by adyasha9** [comment]
@miikkasaxlund I like it very much! You can create a pull request.

**Comment by miikkasaxlund** [comment]
I see that this issue got already solved. Do you still want the changes I made (in a separate branch for example), as I wasn't fast enough to create the PR?

**Comment by adyasha9** [comment]
@miikkasaxlund Yeah sure!

**Comment by miikkasaxlund** [comment]
Great! Could you create a new branch for me so I can create the PR?

**Comment by adyasha9** [comment]
@miikkasaxlund sure

**Comment by adyasha9** [comment]
@miikkasaxlund Sure, I created a 'new' branch you can make changes to that!
